contact_links:
  - name: Feedback & Feature Requests
    url: https://github.com/HomeCord/homecord-app/discussions/new/choose
    about: Have ideas for HomeCord? Post it in our Discussions tab!
  - name: Add App
    url: https://discord.com/oauth2/authorize?client_id=1156152328290840606&permissions=115712&integration_type=0&scope=bot+applications.commands
    about: Want to add HomeCord to your own Server or as a User App? Use this link here!
